In [39]:
# Dependencies
import numpy as np
import pandas as pd
from collections import Counter
from pathlib import Path

from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func


In [4]:
"postgresql://postgres:Foureyes1!@localhost/Capstone"

'postgresql://postgres:Foureyes1!@localhost/Capstone'

In [6]:
db_string = f"postgresql://postgres:Foureyes1!@127.0.0.1:5432/Capstone"

In [8]:
engine = create_engine(db_string)

In [10]:
# Create our session (link) from Python to the DB
session = Session(engine)

In [50]:
happy_2015_df = pd.read_sql_query("select * from world_happiness", con=engine)
happy_2015_df.head(10)

region  happiness_rank  happiness_score  economy_gdp_per_capita   family  \
0      10               1              1.0                 1.39651  1.34951   
1      10               2              1.0                 1.30232  1.40223   
2      10               3              1.0                 1.32548  1.36058   
3      10               4              1.0                 1.45900  1.33095   
4       6               5              1.0                 1.32629  1.32261   
5      10               6              1.0                 1.29025  1.31826   
6      10               7              1.0                 1.32944  1.28017   
7      10               8              1.0                 1.33171  1.28907   
8       1               9              1.0                 1.25018  1.31967   
9       1              10              1.0                 1.33358  1.30923   

   health_life_expectancy  freedom  trust_government_corruption  generosity  
0                 0.94143  0.66557                      0.41978     0.29678  
1                 0.94784  0.62877                      0.14145     0.43630  
2                 0.87464  0.64938                      0.48357     0.34139  
3                 0.88521  0.66973                      0.36503     0.34699  
4                 0.90563  0.63297                      0.32957     0.45811  
5                 0.88911  0.64169                      0.41372     0.23351  
6                 0.89284  0.61576                      0.31814     0.47610  
7                 0.91087  0.65980                      0.43844     0.36262  
8                 0.90837  0.63938                      0.42922     0.47501  
9                 0.93156  0.65124                      0.35637     0.43562

In [30]:
happy_2015_df = happy_2015_df.set_index("region")

In [45]:
happy_2015_df = happy_2015_df.drop(columns=["happiness_rank"], axis=1)

In [46]:
happy_2015_df.head(5)

happiness_score  economy_gdp_per_capita   family  \
region                                                     
10                  1.0                 1.39651  1.34951   
10                  1.0                 1.30232  1.40223   
10                  1.0                 1.32548  1.36058   
10                  1.0                 1.45900  1.33095   
6                   1.0                 1.32629  1.32261   

        health_life_expectancy  freedom  trust_government_corruption  \
region                                                                 
10                     0.94143  0.66557                      0.41978   
10                     0.94784  0.62877                      0.14145   
10                     0.87464  0.64938                      0.48357   
10                     0.88521  0.66973                      0.36503   
6                      0.90563  0.63297                      0.32957   

        generosity  
region              
10         0.29678  
10         0.43630  
10         0.34139  
10         0.34699  
6          0.45811

In [34]:
# Create our features
X = happy_2015_df.drop('happiness_score', axis=1)
X.columns

y = happy_2015_df['happiness_score']

In [35]:
happy_2015_df.columns

Index(['happiness_rank', 'happiness_score', 'economy_gdp_per_capita', 'family',
       'health_life_expectancy', 'freedom', 'trust_government_corruption',
       'generosity'],
      dtype='object')

In [36]:
y.value_counts()

1.0    93
0.0    65
Name: happiness_score, dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [40]:
print(Counter(y_train))
print(Counter(y_test))

Counter({1.0: 69, 0.0: 49})
Counter({1.0: 24, 0.0: 16})


In [55]:
# Random Forest Classifier

In [41]:
# Resample the training data with the BalancedRandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

brfc = BalancedRandomForestClassifier(n_estimators=100, random_state=1)

brfc.fit(X_train, y_train)

BalancedRandomForestClassifier(random_state=1)

In [51]:
y_pred = brfc.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9583333333333333

In [52]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[16  0]
 [ 2 22]]


In [53]:
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

        0.0       0.89      1.00      0.92      0.94      0.96      0.92        16
        1.0       1.00      0.92      1.00      0.96      0.96      0.91        24

avg / total       0.96      0.95      0.97      0.95      0.96      0.92        40



In [68]:
# Easy Ensemble AdaBoost Classifier

In [57]:
from imblearn.ensemble import EasyEnsembleClassifier

eec = EasyEnsembleClassifier(n_estimators=100, random_state=1)


eec.fit(X_train, y_train)


EasyEnsembleClassifier(n_estimators=100, random_state=1)

In [58]:
y_pred = eec.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9791666666666667

In [59]:
from sklearn.metrics import confusion_matrix

confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[16  0]
 [ 1 23]]


In [60]:
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

        0.0       0.94      1.00      0.96      0.97      0.98      0.96        16
        1.0       1.00      0.96      1.00      0.98      0.98      0.95        24

avg / total       0.98      0.97      0.98      0.98      0.98      0.96        40



In [61]:
# Random Oversampling

In [62]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)

X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({1.0: 69, 0.0: 69})

In [63]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='lbfgs', random_state=1)

logreg.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [64]:
y_pred = logreg.predict(X_test)

from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)


0.9791666666666667

In [65]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[16  0]
 [ 1 23]]


In [66]:
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

        0.0       0.94      1.00      0.96      0.97      0.98      0.96        16
        1.0       1.00      0.96      1.00      0.98      0.98      0.95        24

avg / total       0.98      0.97      0.98      0.98      0.98      0.96        40

